[master] improve code style, fix typo, fix undefined function bug

diff --git a/scrsw b/scrsw
--- a/scrsw
+++ b/scrsw
@@ -21,7 +21,7 @@
 # SOFTWARE.
 #
 readonly NAME=scrsw
-readonly VERSION=0.2.0
+readonly VERSION=0.2.1
 
 usage() {
   cat <<-EOS
@@ -78,7 +78,7 @@ _get_next_display_index() {
   local active_display=${active_displays[0]}
   local connected_count=${#connected_displays[@]}
 
-  for d in ${connected_displays[@]}; do
+  for d in "${connected_displays[@]}"; do
     ((next_index++))
     [ "$d" = "$active_display" ] && break
   done
@@ -86,8 +86,9 @@ _get_next_display_index() {
 }
 
 get_next_display() {
-  local index=$(_get_next_display_index)
-  echo ${connected_displays[$index]}
+  local index
+  index=$(_get_next_display_index)
+  echo "${connected_displays[$index]}"
 }
 
 is_in_array() {
@@ -103,14 +104,16 @@ is_optional_param() {
 }
 
 is_last_display() {
-  local index=$(_get_next_display_index)
-  [ $index -eq 0 ] && return 0
+  local index
+  index=$(_get_next_display_index)
+  [ "$index" -eq 0 ] && return 0
   return 1
 }
 
 is_cloned() {
-  local count=$(egrep -c "[0-9]+x[0-9]+\+0\+0" <<< "$xrandr_q")
-  [ $count -eq ${#active_displays[@]} ] && return 0
+  local -i count
+  count=$(egrep -c "[0-9]+x[0-9]+\+0\+0" <<< "$xrandr_q")
+  [ "$count" -eq ${#active_displays[@]} ] && return 0
   return 1
 }
 
@@ -119,15 +122,15 @@ log() {
 }
 
 log_debug() {
-  [ $debug -eq 1 ] && log "debug: $@"
+  [ "$debug" -eq 1 ] && log "debug: $*"
 }
 
 log_info() {
-  [ $verbose -eq 1 ] || [ $debug -eq 1 ] && log "info: $@"
+  [ "$verbose" -eq 1 ] || [ "$debug" -eq 1 ] && log "info: $*"
 }
 
 log_error() {
-  echo -e "error: $@" 1>&2
+  echo -e "error: $*" 1>&2
 }
 
 single_display() {
@@ -140,22 +143,23 @@ single_display() {
 
   log_info "single mode $display"
 
-  for d in ${all_displays[@]}; do
+  for d in "${all_displays[@]}"; do
     if [ "$d" != "$display" ]; then
       args+="--output $d --off "
     fi
   done
   log_debug "xrandr $args --output $display --auto"
-  xrandr $args --output $display --auto
+  # shellcheck disable=SC2086
+  xrandr $args --output "$display" --auto
 }
 
 extend_display() {
   local previous_display
   local args
 
-  log_info "extending $position using ${connected_displays[@]}"
+  log_info "extending $position using ${connected_displays[*]}"
 
-  for d in ${all_displays[@]}; do
+  for d in "${all_displays[@]}"; do
     if is_in_array "$d" "${connected_displays[@]}"; then
       args+="--output $d --auto "
       if [ -n "$previous_display" ]; then
@@ -167,6 +171,7 @@ extend_display() {
     fi
   done
   log_debug "xrandr $args"
+  # shellcheck disable=SC2086
   xrandr $args
 }
 
@@ -174,9 +179,9 @@ clone_display() {
   local previous_display
   local args
 
-  log_info "cloning in mode $mode using ${connected_displays[@]}"
+  log_info "cloning in mode $mode using ${connected_displays[*]}"
 
-  for d in ${all_displays[@]}; do
+  for d in "${all_displays[@]}"; do
     if is_in_array "$d" "${connected_displays[@]}"; then
       args+="--output $d --mode $mode "
       if [ -n "$previous_display" ]; then
@@ -188,6 +193,7 @@ clone_display() {
     fi
   done
   log_debug "xrandr $args"
+  # shellcheck disable=SC2086
   xrandr $args
 }
 
@@ -212,7 +218,7 @@ print_status() {
   elif is_cloned; then
     status=cloned
   fi
-  log "${status}: ${active_displays[@]}\n"
+  log "${status}: ${active_displays[*]}\n"
   log "$xrandr_q"
 }
 
@@ -235,7 +241,7 @@ parse_args() {
             display=$2
             shift
           else
-            log_error "display $2 is not a connected."
+            log_error "display $2 is not connected."
             exit 1
           fi
         fi ;;
@@ -273,7 +279,7 @@ parse_args() {
       -d|--displays)
         if is_optional_param "$2"; then
           display_list=( $(tr ':' '\n' <<< "$2") )
-          for d in ${display_list[@]}; do
+          for d in "${display_list[@]}"; do
             if ! is_in_array "$d" "${connected_displays[@]}"; then
               log_error "display $d is not connected."
               exit 1
@@ -293,7 +299,8 @@ parse_args() {
           post_exec_cmd="$2"
           shift
         else
-          exit_error "$1 expects a command as parameter."
+          log_error "$1 expects a command as parameter."
+          exit 1
         fi ;;
       -v|--verbose)
         verbose=1 ;;
@@ -316,8 +323,8 @@ parse_args() {
 }
 
 configure_displays() {
-  log_debug "connected displays: ${connected_displays[@]}"
-  log_debug "active displays: ${active_displays[@]}"
+  log_debug "connected displays: ${connected_displays[*]}"
+  log_debug "active displays: ${active_displays[*]}"
 
   if [ ${#connected_displays[@]} -eq 1 ]; then
     single_display "${connected_displays[0]}"
